### PR TITLE
Avoid defining convert from Function to NTuple

### PR DESCRIPTION
**Pull request by tkelman**
this is a pretty sketchy method - replace with some inner constructors instead

### CODE REVIEW

**Comment by fredrikekre** [comment]
Thanks! I updated such that it works on both 0.5 and 0.6.

**Comment by tkelman** [comment]
given you had some existing deprecations I wasn't sure how picky you'd be on that, but good call

**Comment by fredrikekre** [comment]
For me it works on both 0.6 and 0.5 without deprecation warnings, but I think there are some dependencies that throw some warnings. Did you get warnings from this package? :confused:

**Comment by tkelman** [comment]
I was just looking at the travis logs, and didn't check too closely exactly where they came from

**Comment by fredrikekre** [comment]
Travis seems to have timed out. Thanks for the fix!

**Pull request merged**
