### PR TITLE
avoid stackoverflow in promotion

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
Some scary test-times on AV... Most notably:

```julia
 ──────────────────────────────────────────────────────────────────────────────
                                       Time                   Allocations      
                               ──────────────────────   ───────────────────────
       Tot / % measured:            1426s / 97.2%           9.37GiB / 96.6%    
 Section               ncalls     time   %tot     avg     alloc   %tot      avg
 ──────────────────────────────────────────────────────────────────────────────
 tensor ops                 1     761s  54.9%    761s   4.68GiB  51.7%  4.68GiB
 constrct Arr               1     304s  21.9%    304s   1.70GiB  18.7%  1.70GiB
 indexing                   1     123s  8.87%    123s    649MiB  7.00%   649MiB
 promotion/conversion       1    39.4s  2.84%   39.4s    230MiB  2.47%   230MiB
 ──────────────────────────────────────────────────────────────────────────────
```

indexing is usually just a couple of seconds, constructing array was 7 seconds on travis... AV brainfreeze or what is going on here?

**Comment by KristofferC** [comment]
I think this is the stuff I saw on my local computer after #19...

**Comment by KristofferC** [comment]
Perhaps revert it and apply again when we go 0.6 only?

**Comment by fredrikekre** [comment]
But it is fast on travis, and it wasn't a problem on AV before... It's weird.

**Pull request merged**
