### PR TITLE
fix evaluating one/zero in generator body

### LINKED ISSUE #7: `@generated` function generators don't follow the new rules for v0.6
The requirements for `@generated` and `@pure` functions have changed in Julia v0.6. For instance, AFAIK you can no longer call any function function from a function generator which may be specialized in the future, or you risk getting a world age error. My understanding of this is that function *generators* are compiled just once, and immediately as they are read in by the system, so they only have access to methods before their definition. Furthermore, any methods found of a later world age will result in a world age related error. I *think* the reason for this is that pure functions and generators do not populate back-edges in the dependency graph for automatic recompilation, but @vtjnash knows the exact details.

A specific example is [this line](https://github.com/KristofferC/Tensors.jl/blob/master/src/constructors.jl#L10) of *Tensors* where `one` and `zero` may fail on user defined types created *after* the user executes `using Tensors`. I haven't looked around for any more problems, but I thought I'd let you know after experience [this](https://github.com/JuliaArrays/StaticArrays.jl/issues/109) in *StaticArrays*.

### PR DESCRIPTION
**Pull request by KristofferC**
This should fix #7 cc @andyferris

### CODE REVIEW

**Comment by KristofferC** [comment]
Heh.. should just put u on review and u did it yourself 17 sec ago... Same wavelength brooo.

**Comment by andyferris** [comment]
I didn't look over the all the codebase - is this the only place that this kind of thing happens? Does it solve the `using` vs `include` error you saw?

**Comment by fredrikekre** [comment]
> Does it solve the using vs include error you saw?

No.

**Comment by KristofferC** [comment]
Problem is here https://github.com/KristofferC/Tensors.jl/blob/49d600a05c07407f410bdf74ebe9eae444748929/src/constructors.jl#L42

I guess it is the same if the type is defined after that function.

**Comment by andyferris** [comment]
Yeah, I saw that and it definitely raised some red flags in my mind, but I didn't exactly know what they were. It seemed a bit like the `similar_type `problem in *StaticArrays* (`similar_type` is the counterpart to `similar` for immutable arrays).

**Comment by KristofferC** [comment]
But it is weird because the Tensor type is defined at that point. We don't expect anyone to subtype these types so we should have it easier than StaticArrays. Anyway, I'm not sure what the difference is between first `include` the module file and then `using` it ... Perhaps the `@generated` stuff runs but the types are still not really defined... I dunno. :/

**Comment by andyferris** [comment]
Unlike most of Julia code, the order of generated functions w.r.t. other method definitions is important, even if they are simultaneously loaded from the same file. Maybe shuffling the order of stuff could help.

Not sure why `using` vs `include` should cause any difference there, however... Seems a mystery to me.

**Comment by fredrikekre** [comment]
> Maybe shuffling the order of stuff could help.

Ref #9 

Thanks for the tip!

**Comment by andyferris** [comment]
No worries. :)

**Pull request merged**
