### PR TITLE
clean up benchmarks

### PR DESCRIPTION
**Pull request by fredrikekre**
- clean up
- add some missing cases
- "pretty printing"

https://gist.github.com/fredrikekre/6fd9e2cededb71fcce907c0985757a3c

### CODE REVIEW

**Comment by KristofferC** [comment]
Just a thing I noticed. This:

```jl
function otimes2{dim}(a::Tensor{2,dim}, b::Tensor{2, dim})
    Tensor{4,dim}(@inline function(i,j,k,l) @inbounds v = a[i,j]*b[k,l]; v end)
end
```

produces the same code as our `otimes`.

**Comment by fredrikekre** [comment]
Thats interesting. But:
```julia
julia> @btime otimes($A, $A);
  4.549 ns (0 allocations: 0 bytes)

julia> @btime otimes2($A, $A);
  11.208 ns (0 allocations: 0 bytes)
```

**Comment by KristofferC** [comment]
I saw that too... makes no sense

**Comment by fredrikekre** [comment]
See my edit above

**Comment by KristofferC** [comment]
Ah!

**Comment by fredrikekre** [comment]
So this turns out to be quite a powerful function then:
https://github.com/KristofferC/Tensors.jl/blob/master/src/constructors.jl#L4-L17

**Comment by KristofferC** [comment]
Yes.

**Comment by fredrikekre** [comment]
Can perhaps simplify a lot with that method?
```julia
@inline function zero2{T}(::Type{Tensor{2, 3, T}})
    Tensor{2, 3}(@inline function(i, j) zero(T); end)
end
```

**Comment by KristofferC** [comment]
Yes, I think so too!

**Comment by KristofferC** [comment]
```
@inline function Base.transpose{dim}(S::Tensor{2, dim})
    Tensor{2, dim}(@inline function(i, j) @inbounds v = S[j,i]; v; end)
end
```

**Comment by fredrikekre** [comment]
`+, -, *, /` as well. I guess it can't be done when there are reductions involved, like `dot`

**Pull request merged**
