### PR TITLE
even better norm...

### PR DESCRIPTION
**Pull request by fredrikekre**
One easy simd implementation.

```julia
julia> @btime norm($A) # PR
  12.102 ns (0 allocations: 0 bytes)
5.381881970369471

julia> @btime norm($A) # master
  21.513 ns (0 allocations: 0 bytes)
5.38188197036947
```

### CODE REVIEW

**Comment by KristofferC** [comment]
This should work for all dimensions. Compiler should unroll by itself if loop is short enough.

**Comment by KristofferC** [comment]
I wonder if `sqrt(sum(abs2, S))` is as fast?

**Comment by fredrikekre** [comment]
No, `sqrt(mapreduce(abs2, +, S))` was much faster than `sqrt(sum(abs2, S))`

**Comment by KristofferC** [comment]
It unrolls it automatically for `dim < 3`.

**Comment by fredrikekre** [comment]
close in favor of #15

**Pull request closed without merging**
