### PR TITLE
add Project.toml

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
> Stdlibs also?

Yea, I just got a `LinearAlgebra not installed` :)

Do we need the `version` field? If so, what should it be?

**Comment by KristofferC** [comment]
Doesn't really matter, can put the current.

**Comment by fredrikekre** [comment]
```
ERROR: GitError(Code:ERROR, Class:Invalid, reference 'HEAD' is neither a local nor a remote branch.)
Stacktrace:
 [1] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LibGit2/src/error.jl:98 [inlined]
 [2] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LibGit2/src/reference.jl:122 [inlined]
 [3] macro expansion at ./gcutils.jl:82 [inlined]
 [4] branch(::LibGit2.GitReference) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LibGit2/src/reference.jl:121
 [5] branch(::LibGit2.GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/LibGit2/src/LibGit2.jl:371
 [6] #handle_repos_add!#16(::Bool, ::Function, ::Pkg3.Types.Context, ::Array{Pkg3.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/Types.jl:733
 [7] #handle_repos_add! at ./<missing>:0 [inlined]
 [8] #add_or_develop#8(::Symbol, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg3.Types.Context, ::Array{Pkg3.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:31
 [9] #add_or_develop at ./<missing>:0 [inlined]
 [10] #add_or_develop#7 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:22 [inlined]
 [11] #add_or_develop at ./<missing>:0 [inlined]
 [12] #add_or_develop#6 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:21 [inlined]
 [13] #add_or_develop at ./<missing>:0 [inlined]
 [14] #add_or_develop#5 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:20 [inlined]
 [15] #add_or_develop at ./<missing>:0 [inlined]
 [16] #add#9 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:43 [inlined]
 [17] add at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:43 [inlined]
 [18] clone(::String, ::Vararg{String,N} where N) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg3/src/API.jl:389
 [19] top-level scope
```

**Comment by KristofferC** [comment]
Ah, yep I've fixed that on Pkg3 master. Will merge to Base and we can try again.

**Comment by KristofferC** [comment]
TimerOutputs is a test dep I think

**Pull request merged**
