### PR TITLE
Fix zeros and ones

### PR DESCRIPTION
**Pull request by fredrikekre**
fix the test failure from #53

### CODE REVIEW

**Comment by fredrikekre** [comment]
Hmm actually it was enought to speify `Int`:

```diff
diff --git a/src/constructors.jl b/src/constructors.jl
index ab8ee10..ffed041 100644
--- a/src/constructors.jl
+++ b/src/constructors.jl
@@ -103,8 +103,8 @@ Base.fill{T <: AbstractTensor}(el::Number, S::Type{T}) = apply_all(get_base(T),
 Base.fill{T <: AbstractTensor}(f::Function, S::Type{T}) = apply_all(get_base(T), i -> f())
 
 # Array with zero/ones
-@inline Base.zeros{T <: AbstractTensor}(::Type{T}, dims...) = fill(zero(T), dims...)
-@inline Base.ones{T <: AbstractTensor}(::Type{T}, dims...) = fill(one(T), dims...)
+@inline Base.zeros{T <: AbstractTensor}(::Type{T}, dims::Int...) = fill(zero(T), dims...)
+@inline Base.ones{T <: AbstractTensor}(::Type{T}, dims::Int...) = fill(one(T), dims...)
 
 # diagm
 @generated function Base.diagm{T <: SecondOrderTensor}(S::Type{T}, v::Union{AbstractVector, Tuple})
```

**Comment by KristofferC** [comment]
Thanks!

**Comment by fredrikekre** [comment]
I think it must have taken another path, and made an `Array{T}` where `T = Tensor{2, 3, T, M}` instead of creating the array for the specific type, since `T` is not concrete

**Comment by KristofferC** [comment]
Yeah, sounds reasonable.

**Comment by fredrikekre** [comment]
I wonder if https://github.com/JuliaLang/julia/blob/master/base/array.jl#L250 should instead be 

```julia
$fname(T::Type, dims::Tuple) = fill!(Array{typeof($felt(T))}(Dims(dims)), $felt(T))
```
?

**Pull request merged**
