### PR TITLE
[WIP] Implement new eigenvalue solver

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fredrikekre** [comment]
On this branch, test this:

```julia
using Tensors, BenchmarkTools
A = rand(SymmetricTensor{2, 3});
@btime eigfact($A); # this wraps in Eigen
@btime eigfact2($A); # this returns tuple
```

**Comment by KristofferC** [comment]
0.6:

```
julia> A = rand(SymmetricTensor{2, 3});

julia> @btime eigfact($A); # this wraps in Eigen
  170.208 ns (0 allocations: 0 bytes)

julia> @btime eigfact2($A); # this returns tuple
  154.999 ns (0 allocations: 0 bytes)
```

**Comment by fredrikekre** [comment]
Hmm no allocations at least. Why is it faster though?

**Comment by fredrikekre** [comment]
Is the licensing OK?

**Comment by KristofferC** [comment]
Yes

**Pull request merged**
