### PR TITLE
0.5 fix for AD

### PR DESCRIPTION
**Pull request by fredrikekre**
This fixes AD on 0.5, so lets merge this first and then rebase #58

### CODE REVIEW

**Comment by KristofferC** [comment]
What is the problem with AD on 0.5 again?

**Comment by fredrikekre** [comment]
Its only such that it will work with ForwardDiff master, where this happens now:
```julia
julia> v = rand(Vec{3}); gradient(norm, v)
3-element Tensors.Tensor{1,3,ForwardDiff.Dual{Void,Float64,3},3}:
 Dual{Void}(0.0,0.0,0.0,0.0)
 Dual{Void}(0.0,0.0,0.0,0.0)
 Dual{Void}(0.0,0.0,0.0,0.0)
```

**Comment by fredrikekre** [comment]
Basically `Dual{N, T}` have changed to `Dual{Tag, T, N}`

**Comment by KristofferC** [comment]
But 0.5 support was dropped from ForwardDiff for that change?

**Comment by fredrikekre** [comment]
Right... Then #58 is enough

**Pull request closed without merging**
